"""dev_add_columns_in_books

Revision ID: 7615c3157d55
Revises: 98724dfe8121
Create Date: 2025-07-13 22:40:03.203655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7615c3157d55'
down_revision: Union[str, Sequence[str], None] = '98724dfe8121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('cover', sa.String(), nullable=True))
    op.add_column('books', sa.Column('description', sa.String(), nullable=True))
    op.add_column('books', sa.Column('rating', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'rating')
    op.drop_column('books', 'description')
    op.drop_column('books', 'cover')
    # ### end Alembic commands ###
