"""dev_add_unique_in_books

Revision ID: 98724dfe8121
Revises: a2242db2956e
Create Date: 2025-07-13 21:55:14.207556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98724dfe8121'
down_revision: Union[str, Sequence[str], None] = 'a2242db2956e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'public_year',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    op.create_unique_constraint('uq_book_unique_fields', 'books', ['title', 'author', 'public_year', 'genre'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_book_unique_fields', 'books', type_='unique')
    op.alter_column('books', 'public_year',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
