"""dev_rename_column_cover_in_books

Revision ID: af755ba6da38
Revises: 7615c3157d55
Create Date: 2025-07-15 20:29:11.847154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af755ba6da38'
down_revision: Union[str, Sequence[str], None] = '7615c3157d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('cover_url', sa.String(), nullable=True))
    op.drop_column('books', 'cover')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('cover', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('books', 'cover_url')
    # ### end Alembic commands ###
